baseurl: "http://deprode.github.io/esa-blog"
langageCode: "ja"

title: "log"
copyright: "deprode"

publishDir: "docs"
builddrafts: false
footnotereturnlinkcontents: "↩"
HasCJKLanguage: true

permalinks:
  post: "/:year/:month/:day/:filename/"
  page: "/:title/"
params:
  author: "deprode"
  github: "deprode"
  twitter: "@deproden"